services:
  caddy:
    build:
      context: ../..  # Points to the root of caddy-failover repository
      dockerfile: Dockerfile
      target: standard  # Use the standard caddy target (not loaded)
    labels:
      # Logging configuration
      - "dev.dozzle.group=infrastructure"
    ports:
      - "${CADDY_HTTPS_PORT:-9443}:9443"  # HTTPS entry point (different from Traefik's 8443)
      - "${CADDY_HTTP_PORT:-9080}:9080"   # HTTP entry point (different from Traefik's 8080)
      # Admin API is now accessible via HTTPS at https://localhost:9443/caddy-admin/
      # Internal port 2019 is still used for health checks but not exposed
    volumes:
      # Configuration - using native Caddyfile format with failover plugin
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # Docker socket for future Docker label support
      - type: bind
        source: ${DOCKER_SOCK_PATH:-/var/run/docker.sock}
        target: /var/run/docker.sock
      # Caddy data directory for certificates and state
      - caddy_data:/data
      - caddy_config:/config
    environment:
      # Caddy environment variables
      CADDY_ADMIN: :2019
      # Optional: Set log level
      CADDY_LOG_LEVEL: ${CADDY_LOG_LEVEL:-DEBUG}
      DOCKER_HOST_URI: ${DOCKER_HOST_URI:-host.docker.internal}
    # networks:
    #   - default
    restart: unless-stopped
    # depends_on:
    #   # Ensure core services are available
    #   - postgres
    #   - redis

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
