name: Test Plugin

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: |
          go mod download
          go mod verify

      - name: Run go fmt
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Please run 'gofmt -s -w .' to format your code"
            gofmt -s -d .
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run unit tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Run tests with race detector
        run: go test -race -short ./...

      - name: Upload coverage to Codecov
        if: matrix.go-version == '1.22'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run benchmarks
        run: go test -bench=. -benchmem -run=^$ ./...

  build-and-validate:
    name: Build and Validate Plugin
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build Caddy with plugin
        run: |
          xcaddy build \
            --with github.com/ejlevin1/caddy-failover=.

      - name: Test plugin build
        run: |
          ./caddy version
          ./caddy list-modules | grep failover_proxy
          ./caddy list-modules | grep failover_status

      - name: Validate basic Caddyfile
        run: |
          ./caddy validate --config testdata/basic.Caddyfile --adapter caddyfile

      - name: Validate complex Caddyfile
        run: |
          # Set dummy environment variables for complex Caddyfile
          export API_PRIMARY_URL=http://localhost:5031
          export API_SECONDARY_URL=http://localhost:5032
          ./caddy validate --config testdata/complex.Caddyfile --adapter caddyfile


  integration-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run integration tests
        run: |
          go test -v -tags=integration ./...
